Updated buildscript.sh as the Linux tree had to be built from some other workspace since a previous workspace throws a mysterious error which was not occurring in earlier builds as below (which looks to be arch issue,but nothing changed in the meantime):
kernel/bounds.c:1: error: code model ‘kernel’ not supported in the 32 bit mode
kernel/bounds.c:1: sorry, unimplemented: 64-bit mode not compiled in